name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/*
jobs:
  unit-test:
    uses: categolj/workflows/.github/workflows/unit-test.yaml@main
    secrets:
      MAVEN_SERVER_ID: ${{ secrets.GF_SERVER_ID }}
      MAVEN_USERNAME: ${{ secrets.GF_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.GF_PASSWORD }}
  build-oci-image-jvm-amd64:
    needs: unit-test
    uses: categolj/workflows/.github/workflows/build-oci-image-jvm.yaml@main
    with:
      image_name: jvm_amd64
      image_file: jvm_amd64.yaml
      runs_on: ubuntu-latest
    secrets:
      MAVEN_SERVER_ID: ${{ secrets.GF_SERVER_ID }}
      MAVEN_USERNAME: ${{ secrets.GF_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.GF_PASSWORD }}
  build-oci-image-jvm-aarch64:
    needs: unit-test
    uses: categolj/workflows/.github/workflows/build-oci-image-jvm.yaml@main
    with:
      image_name: jvm_aarch64
      image_file: jvm_aarch64.yaml
      runs_on: ubuntu-24.04-arm
    secrets:
      MAVEN_SERVER_ID: ${{ secrets.GF_SERVER_ID }}
      MAVEN_USERNAME: ${{ secrets.GF_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.GF_PASSWORD }}
  push-multi-arch-image-jvm:
    needs:
    - build-oci-image-jvm-amd64
    - build-oci-image-jvm-aarch64
    uses: categolj/workflows/.github/workflows/push-multi-arch-image.yaml@main
    with:
      prefix: jvm
  save-image-jvm-amd64:
    needs: build-oci-image-jvm-amd64
    uses: categolj/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: jvm_amd64
      image_file: jvm_amd64.yaml
  save-image-jvm-aarch64:
    needs: build-oci-image-jvm-aarch64
    uses: categolj/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: jvm_aarch64
      image_file: jvm_aarch64.yaml
